import 'package:flutter/material.dart';

import '../../l10n/l10n.dart';
import '../theme.dart';

/// Quick reactions, as on WhatsApp.
const quickReactions = ['👍', '❤️', '😂', '😮', '😢', '🙏'];

const _emojiGroups = <(IconData, List<String>)>[
  (
    Icons.emoji_emotions_outlined,
    [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '😂',
      '🤣',
      '😊',
      '😇',
      '🙂',
      '🙃',
      '😉',
      '😌',
      '😍',
      '🥰',
      '😘',
      '😗',
      '😙',
      '😚',
      '😋',
      '😛',
      '😝',
      '😜',
      '🤪',
      '🤨',
      '🧐',
      '🤓',
      '😎',
      '🥳',
      '😏',
      '😒',
      '😞',
      '😔',
      '😟',
      '😕',
      '🙁',
      '☹️',
      '😣',
      '😖',
      '😫',
      '😩',
      '🥺',
      '😢',
      '😭',
      '😤',
      '😠',
      '😡',
      '🤯',
      '😳',
      '🥵',
      '🥶',
      '😱',
      '😨',
      '😰',
      '😥',
      '😓',
      '🤗',
      '🤔',
      '🤭',
      '🤫',
      '🤥',
      '😶',
      '😐',
      '😑',
      '😬',
      '🙄',
      '😯',
      '😦',
      '😧',
      '😮',
      '😲',
      '🥱',
      '😴',
      '🤤',
      '😪',
      '😵',
      '🤐',
      '🥴',
      '🤢',
      '🤮',
      '🤧',
      '😷',
      '🤒',
      '🤕',
      '🤑',
      '🤠',
      '😈',
      '👻',
      '💯',
    ],
  ),
  (
    Icons.waving_hand_outlined,
    [
      '👋',
      '🤚',
      '🖐️',
      '✋',
      '🖖',
      '👌',
      '🤌',
      '🤏',
      '✌️',
      '🤞',
      '🤟',
      '🤘',
      '🤙',
      '👈',
      '👉',
      '👆',
      '👇',
      '☝️',
      '👍',
      '👎',
      '✊',
      '👊',
      '🤛',
      '🤜',
      '👏',
      '🙌',
      '👐',
      '🤲',
      '🤝',
      '🙏',
      '✍️',
      '💪',
      '🦾',
      '👀',
      '👶',
      '🧒',
      '👦',
      '👧',
      '🧑',
      '👨',
      '👩',
      '🧓',
      '👴',
      '👵',
      '🧕',
      '👳',
      '👲',
      '🤵',
      '👰',
      '🤰',
      '🤱',
      '👪',
      '👨‍👩‍👧',
      '👨‍👩‍👧‍👦',
      '🧑‍🎓',
      '🧑‍🏫',
      '🧑‍⚕️',
      '🧑‍🌾',
      '🧑‍🍳',
      '🧑‍💻',
      '🧑‍🔧',
      '🧑‍💼',
      '🚶',
      '🏃',
      '🙋',
      '🙇',
      '🤦',
      '🤷',
    ],
  ),
  (
    Icons.favorite_border,
    [
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '🤎',
      '💔',
      '❣️',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
      '💘',
      '💝',
      '✨',
      '⭐',
      '🌟',
      '💫',
      '🔥',
      '🎉',
      '🎊',
      '🎈',
      '🎁',
      '🏆',
      '🥇',
      '🎓',
      '💐',
      '🌹',
      '🌸',
      '🌺',
      '🌻',
      '🌷',
    ],
  ),
  (
    Icons.mosque_outlined,
    [
      '🕌',
      '🤲',
      '📿',
      '☪️',
      '🌙',
      '🌛',
      '⭐',
      '🕋',
      '📖',
      '🕯️',
      '🐑',
      '🐄',
      '🐪',
      '🌴',
      '🍲',
      '🥘',
      '🍛',
      '🍚',
      '🍗',
      '🥩',
      '🍞',
      '🫓',
      '🥛',
      '🍵',
      '☕',
      '🧃',
      '🍉',
      '🥭',
      '🍌',
      '🍊',
      '🥜',
      '🌽',
      '🍯',
      '🍬',
      '🍰',
      '🎂',
    ],
  ),
  (
    Icons.home_outlined,
    [
      '🏠',
      '🏡',
      '🏫',
      '🏥',
      '🏦',
      '🕌',
      '🚗',
      '🚕',
      '🚌',
      '🏍️',
      '✈️',
      '🚆',
      '⛽',
      '📱',
      '💻',
      '📷',
      '📞',
      '☎️',
      '📅',
      '⏰',
      '⌛',
      '💡',
      '📚',
      '✏️',
      '📝',
      '📌',
      '📎',
      '✂️',
      '🔑',
      '💰',
      '💵',
      '💳',
      '🛒',
      '🎵',
      '⚽',
      '🏀',
      '☀️',
      '🌤️',
      '⛅',
      '🌧️',
      '⛈️',
      '🌈',
      '❄️',
      '🌊',
      '🌍',
      '✅',
      '❌',
      '⚠️',
      '❓',
      '❗',
      '➕',
      '👉',
      '🆗',
      '🆕',
    ],
  ),
];

/// Emoji to tap into the message box (in place of the keyboard, as on WhatsApp).
class EmojiPanel extends StatefulWidget {
  const EmojiPanel({super.key, required this.onPick, this.height = 260});

  final ValueChanged<String> onPick;
  final double height;

  @override
  State<EmojiPanel> createState() => _EmojiPanelState();
}

class _EmojiPanelState extends State<EmojiPanel> {
  int _group = 0;

  @override
  Widget build(BuildContext context) {
    final emojis = _emojiGroups[_group].$2;
    return SizedBox(
      height: widget.height,
      child: Column(
        children: [
          Row(
            children: [
              for (final (i, g) in _emojiGroups.indexed)
                Expanded(
                  child: IconButton(
                    isSelected: i == _group,
                    color: Bua.inkSubtle,
                    selectedIcon: Icon(g.$1, color: Bua.green),
                    icon: Icon(g.$1),
                    onPressed: () => setState(() => _group = i),
                  ),
                ),
            ],
          ),
          Divider(height: 1, color: Bua.line),
          Expanded(
            child: GridView.builder(
              padding: const EdgeInsets.all(6),
              gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 44),
              itemCount: emojis.length,
              itemBuilder: (_, i) => InkWell(
                borderRadius: BorderRadius.circular(8),
                onTap: () => widget.onPick(emojis[i]),
                child: Center(child: Text(emojis[i], style: const TextStyle(fontSize: 26))),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// Every emoji, to pick one reaction from (the "+" after the quick ones).
Future<String?> pickEmoji(BuildContext context) => showModalBottomSheet<String>(
  context: context,
  showDragHandle: true,
  builder: (c) => SafeArea(
    child: Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(context.l10n.dmChooseReaction, style: Theme.of(c).textTheme.titleMedium),
        EmojiPanel(height: 320, onPick: (e) => Navigator.pop(c, e)),
      ],
    ),
  ),
);

final _emojiOnly = RegExp(
  r'^[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2300}-\u{23FF}\u{2B00}-\u{2BFF}\u{2190}-\u{21FF}'
  r'\u{3030}\u{303D}\u{3297}\u{3299}\u{00A9}\u{00AE}\u{203C}\u{2049}\u{2122}\u{2139}'
  r'\u{200D}\u{FE0F}\u{20E3}\s]+$',
  unicode: true,
);

/// Up to three emoji and nothing else: shown large, as on WhatsApp.
bool isBigEmoji(String text) {
  final t = text.trim();
  if (t.isEmpty || !_emojiOnly.hasMatch(t)) return false;
  return t.characters.where((c) => c.trim().isNotEmpty).length <= 3;
}
